version: '3'
services:
  proxy:
    container_name: "proxy-server"
    image: nginx:latest
    depends_on:
      - auth
    ports:
      - "80:80"
    volumes:
        - $HOME/conf/nginx.conf:/etc/nginx/nginx.conf
  auth:
    container_name: "auth-server"
    image: nmrhtn7898/bread-auth-module
    expose:
      - "9600"
    env_file:
      - $HOME/conf/docker.env
    environment:
      ACTIVE_PROFILE: "dev"