language: java
jdk:
  - openjdk8

services:
  - docker

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew

stages:
  - dev

# 멀티 모듈 프로젝트이므로 특정 모듈만을 배포해야하는 경우는 배포를 원하지 않는 모듈의 name의 job을 주석 처리 후, 리포지토리에 commit
# 배포하는 모듈은 version 정보를 수정해줘야함, 다른 좋은 방법이 있는지 아직 찾이 못했음... 젠킨스 사용해야하는지?
jobs:
  include:
    - stage: dev
#      name: "integration test"
#      script: ./gradlew clean build
#      after_success:
#        - ./gradlew jacocoRootReport coveralls

    - name: "bread-auth-module deploy"
      script: bash docker/travis-docker.sh
      env: MODULE_NAME=bread-auth-module MODULE_VERSION=0.0.1 DOCKER_USERNAME=nmrhtn7898
      before_deploy:
        - cd $MODULE_NAME
        - zip -r $MODULE_NAME *
        - mkdir -p deploy
        - mv $MODULE_NAME.zip deploy/$MODULE_NAME.zip
        - cd ..
      deploy:
        - provider: s3
          access_key_id: $AWS_ACCESS_KEY
          secret_access_key: $AWS_SECRET_KEY
          bucket: bread-app
          region: ap-northeast-2
          skip_cleanup: true
          acl: public_read
          wait-until-deployed: true
          local_dir: $MODULE_NAME/deploy
          upload-dir: $MODULE_NAME
          on:
            repo: nmrhtn7898/bread-project
            branch: master
        - provider: codedeploy
          access_key_id: $AWS_ACCESS_KEY
          secret_access_key: $AWS_SECRET_KEY
          bucket: bread-app
          key: $MODULE_NAME/$MODULE_NAME.zip
          bundle_type: zip
          application: bread-deploy-app
          deployment_group: bread-deploy-group
          region: ap-northeast-2
          wait-until-deployed: true
          on:
            repo: nmrhtn7898/bread-project
            branch: master

#    - name: "bread-api-module deploy"
#      script: bash docker/travis-docker.sh
#      env: MODULE_NAME=bread-api-module MODULE_VERSION=0.0.1 DOCKER_USERNAME=nmrhtn7898
#      before_deploy:
#        - cd $MODULE_NAME
#        - zip -r $MODULE_NAME *
#        - mkdir -p deploy
#        - mv $MODULE_NAME.zip deploy/$MODULE_NAME.zip
#      deploy:
#        - provider: s3
#          access_key_id: $AWS_ACCESS_KEY
#          secret_access_key: $AWS_SECRET_KEY
#          bucket: bread-app
#          region: ap-northeast-2
#          skip_cleanup: true
#          acl: public_read
#          wait-until-deployed: true
#          local_dir: deploy
#          upload-dir: $MODULE_NAME
#          on:
#            repo: nmrhtn7898/bread-project
#            branch: master
#        - provider: codedeploy
#          access_key_id: $AWS_ACCESS_KEY
#          secret_access_key: $AWS_SECRET_KEY
#          bucket: bread-app
#          key: $MODULE_NAME.zip
#          bundle_type: zip
#          application: bread-deploy-app
#          deployment_group: bread-deploy-group
#          region: ap-northeast-2
#          wait-until-deployed: true
#          on:
#            repo: nmrhtn7898/bread-project
#            branch: master

#notifications:
#  email:
#    recipients:
#      - nmrhtn7898@naver.com
