./gradlew createDockerImage
docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
./gradlew :$MODEUL_NAME:clean build
docker tag $DOCKER_USERNAME/$:$MODULE_VERSION $DOCKER_USERNAME/MODULE_NAME
docker push $DOCKER_USERNAME/MODULE_NAME:$MODULE_VERSION
docker push $DOCKER_USERNAME/MODULE_NAME:$MODULE_VERSION