= API Guide
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

Auth API는 인증 서비스를 제공합니다.


[[authorization-code-with-pkce-grant]]
== 코드 발급 - Authorization Code With PKCE

- `GET` 요청 및 `AUTHORIZATION CODE WITH PKCE` 방식을 사용하여 엑세스 토큰과 교환하기 위한 코드를 발급받을 수 있습니다.

operation::authorization-code-with-pkce-grant[snippets='http-request,request-parameters']


[[token-authorization-code-with-pkce-grant]]
== 엑세스 토큰 발급 - Authorization Code With PKCE

- `POST` 요청 및 `AUTHORIZATION CODE WITH PKCE` 방식을 사용하여 엑세스 토큰을 발급받을 수 있습니다. +
- `client_secret` 을 사용하지 않는 `public client` 인 경우 `client(browser, mobile 등)` 에 따라 `refresh_token` 을 제공하지 않을 수 있습니다.

operation::token-authorization-code-with-pkce-grant[snippets='curl-request,http-request,request-headers,request-parameters,http-response,response-headers,response-body,response-fields']
//
//[[token-authorization-code-grant]]
//=== 엑세스 토큰 발급 - Authorization Code 방식
//
//`POST` 요청 및 `AUTHORIZATION CODE` 방식을 사용하여 엑세스 토큰을 발급받을 수 있습니다.
//
//operation::token-authorization-code-grant[snippets='curl-request,http-request,request-headers,request-parameters,http-response,response-headers,response-body,response-fields']
//



[[token-password-grant]]
== 엑세스 토큰 발급 - Password

- `POST` 요청 및 `PASSWORD` 방식을 사용하여 엑세스 토큰을 발급받을 수 있습니다. +
- `client_secret` 을 사용하지 않는 `public client` 인 경우 `client(browser, mobile 등)` 에 따라 `refresh_token` 을 제공하지 않을 수 있습니다.

operation::token-password-grant[snippets='curl-request,http-request,request-headers,request-parameters,http-response,response-headers,response-body,response-fields']



[[token-refresh-token-grant]]
== 엑세스 토큰 발급 - Refresh Token

- `POST` 요청 및 `REFRESH TOKEN` 방식을 사용하여 엑세스 토큰을 인증 없이 발급받을 수 있습니다.

operation::token-refresh-token-grant[snippets='curl-request,http-request,request-headers,request-parameters,http-response,response-headers,response-body,response-fields']
//
//[[token-client-credentials-grant]]
//=== 엑세스 토큰 발급 - Client Credentials 방식
//
//`POST` 요청 및 'CLIENT CREDENTIALS' 방식을 사용하여 엑세스 토큰을 인증 없이 발급받을 수 있다.
//
//operation::token-client-credentials-grant[snippets='curl-request,http-request,request-headers,request-parameters,http-response,response-headers,response-body,response-fields']


[[check-token]]
== 엑세스 토큰 확인

- `POST` 요청으로 엑세스 토큰의 유효성을 확인할 수 있습니다.

operation::check-token[snippets='curl-request,http-request,request-headers,request-parameters,http-response,response-headers,response-body,response-fields']