= API Guide
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request

Auth API는 인증 서비스를 제공합니다.


[[authorization-code-with-pkce-grant]]
== 인가 코드 발급 - Authorization Code With PKCE

TIP: link:https://oauth.net/2/pkce/[PKCE flow] 란? 토큰 발급에 필요한 인가 코드를 탈취하는 공격을 막기 위한 확장 인증 플로우입니다. +
`Code Verifier` 는 최소 43 ~ 최대 128 자의 A-Z, a-z, 0-9, -(hypen), .(period), _(underscore), ~(tilde) 문자로 이루어진 랜덤 문자열입니다. +
`Code Challenge Method` 는 `Code Verifier` 을 암호화 하기 위한 단방향 알고리즘(SHA 256)입니다. +
`Code Challenge` 는 `Code Verifier` 을 `Code Challenge Method` 알고리즘으로 암호화한 후 BASE 64 인코딩한 값 입니다. +
토큰 발급 시 `Code Verifier` 을 전달하여 인가 코드를 발급받을 때 전달했던 `Code Challenge` 값과 비교하여 일치한 경우에 토큰을 발급합니다. +

- `GET` 요청 및 `Authorization Code With PKCE` 방식을 사용하여 토큰과 교환하기 위한 인가 코드를 발급받을 수 있습니다.

operation::authorization-code-with-pkce-grant-get[snippets='http-request,request-parameters']
operation::authorization-code-with-pkce-grant-post[snippets='http-response']


[[token-authorization-code-with-pkce-grant]]
== 토큰 발급 - Authorization Code With PKCE

- `POST` 요청 및 `Authorization Code With PKCE` 방식을 사용하여 인가 코드로 토큰을 발급받을 수 있습니다.
- `client_secret` 을 사용하지 않는 `public client` 인 경우 `client_secret` 을 전달하지 않습니다.
- `public client` 는 `client(browser, mobile)` 에 따라 `refresh_token` 을 제공하지 않을 수 있습니다.

operation::token-authorization-code-with-pkce-grant[snippets='http-request,request-parameters,http-response,response-fields']




[[token-password-grant]]
== 토큰 발급 - Resource Owner Password Credentials

- `POST` 요청 및 `Resource Owner Password Credentials` 방식을 사용하여 토큰을 발급받을 수 있습니다.
- `client_secret` 을 사용하지 않는 `public client` 인 경우 `client_secret` 을 전달하지 않습니다.
- `public client` 는 `client(browser, mobile)` 에 따라 `refresh_token` 을 제공하지 않을 수 있습니다.

operation::token-password-grant[snippets='http-request,request-parameters,http-response,response-fields']



[[token-refresh-token-grant]]
== 토큰 발급 - Refresh Token

- `POST` 요청 및 `Refresh Token` 방식을 사용하여 토큰을 재인증 없이 발급받을 수 있습니다.

operation::token-refresh-token-grant[snippets='http-request,request-parameters,http-response,response-fields']




[[check-token]]
== 토큰 검증

- `POST` 요청으로 토큰의 유효성을 확인할 수 있습니다.
- 요청 헤더 `Authorization` 를 통해 `client_id + ':' + client_secret` 문자열을 BASE 64 인코딩한 값을 전달합니다.

operation::check-token[snippets='http-request,request-headers,request-parameters,http-response,response-fields']