version: '3'
services:
  proxy-server:
    container_name: "proxy-server"
    image: nginx:latest
    depends_on:
      - bakery-auth-server
      - bakery-api-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $HOME/conf/nginx.conf:/etc/nginx/nginx.conf
      - $HOME/conf/dev/bakery-app.tk:/var/dev/bakery-app.tk
    environment:
      AUTH_SERVER_PORT: "9600"
      API_SERVER_PORT: "8600"
    build:
      context: .
      dockerfile: $HOME/conf/Dockerfile
  bakery-auth-server:
    container_name: "bakery-auth-server"
    image: nmrhtn7898/bakery-auth-server:${TAG}
    expose:
      - "9600"
    env_file:
      - $HOME/conf/docker.env
    environment:
      ACTIVE_PROFILE: "dev"
  bakery-api-server:
    container_name: "bakery-api-server"
    image: nmrhtn7898/bakery-api-server:${TAG}
    expose:
      - "8600"
    env_file:
      - $HOME/conf/docker.env
    environment:
      ACTIVE_PROFILE: "dev"