version: '3'
services:
  proxy-server:
    container_name: "proxy-server"
    image: nginx:latest
    depends_on:
      - bread-auth-module
      - bread-api-module
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $HOME/conf/nginx.conf:/etc/nginx/nginx.conf
      - $HOME/conf/www/dev.bread-project.tk:/var/www/dev.bread-project.tk
  bread-auth-module:
    container_name: "bread-auth-module"
    image: nmrhtn7898/bread-auth-module:${TAG}
    expose:
      - "9600"
    env_file:
      - $HOME/conf/docker.env
    environment:
      ACTIVE_PROFILE: "dev"
  bread-api-module:
    container_name: "bread-api-module"
    image: nmrhtn7898/bread-api-module:${TAG}
    expose:
      - "8600"
    env_file:
      - $HOME/conf/docker.env
    environment:
      ACTIVE_PROFILE: "dev"