version: '3'
services:
  database:
    container_name: "database-server"
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "bakery"
    volumes:
      - ./database:/var/lib/mysql
  redis:
    container_name: "redis-server"
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
