./gradlew :$MODULE_NAME:clean build createDockerImage
docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
docker tag $DOCKER_USERNAME/$MODULE_NAME:$MODULE_VERSION $DOCKER_USERNAME/MODULE_NAME
docker push $DOCKER_USERNAME/MODULE_NAME:$MODULE_VERSION
docker push $DOCKER_USERNAME/MODULE_NAME