version: '3'
services:
  database:
    container_name: "database-server"
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "bread"
    volumes:
      - ./database:/var/lib/mysql
  redis:
    container_name: "redis-server"
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
  proxy:
    container_name: "proxy-server"
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
