jasypt:
  encryptor:
    bean: stringEncryptor

server:
  port: 8600

spring:
  datasource:
    url: ENC(8zUm3Zjwvp5648B6Q2IaaJF74pRlBe8iGTM3xVTJvhnV5JroKiXd4j6IAnp5EnRv5QZJ1mSq2XwBaD2s3QcPiVBOxtUKhcGO4NYvAN/rsZPuLFxldz0l7GhM524cjyfpcWxImJpwTzjldRe8ZfNj0t0gk3qsHMogvO3ybiLt26/7i5ChuBMgTO/lb773POA6PqkwlrilERtzKJ/28GsMzA==)
    username: ENC(yGCjrkqEv7bGJxbFGiMdDQ==)
    password: ENC(s0TLJNiPYXqZNADpH30mWsn32X3WqAIo)
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ENC(fzl+X/qnBYq7tAkdI15VpE0xXQAoebXxFD6UIym0jiqU75JyPki1EqJ3aGu4gT7J+bv2mB/zpHGx/VQpk6vMSQ==)
    port: 6379

jwt:
  publicKey:
    location: classpath:/publicKey-dev.txt

logging:
  level:
    org:
      springframework:
        security: DEBUG