server:
  port: 8600

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bread?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false
  redis:
    host: localhost
    port: 6379

jwt:
  signKey: temp_signkey

auth:
  domain:
    url: http://localhost:9600

client:
  id: test
  secret: 1234

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        security: DEBUG