version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/deploy/bread-auth-module
permissions:
  - object: /home/ec2-user/
    mode: 777
    type:
      - file
hooks:
  AfterInstall: # 배포가 끝나면 아래 명령어를 실행
    - location: /home/ec2-user/deploy/bread-auth-module/src/docker/execute-deploy.sh
      timeout: 180
      runas: root