server:
  port: 9600

jasypt:
  encryptor:
    bean: stringEncryptor

spring:
  datasource:
    url: ENC(8zUm3Zjwvp5648B6Q2IaaJF74pRlBe8iGTM3xVTJvhnV5JroKiXd4j6IAnp5EnRv5QZJ1mSq2XwBaD2s3QcPiVBOxtUKhcGO4NYvAN/rsZPuLFxldz0l7GhM524cjyfpcWxImJpwTzjldRe8ZfNj0t0gk3qsHMogvO3ybiLt26/7i5ChuBMgTO/lb773POA6PqkwlrilERtzKJ/28GsMzA==)
    username: ENC(yGCjrkqEv7bGJxbFGiMdDQ==)
    password: ENC(s0TLJNiPYXqZNADpH30mWsn32X3WqAIo)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE